---
title: "HW2"
author: "Dongkeoon Oh"
date: "2018<eb>뀈 8<ec>썡 14<ec>씪"
output:
  pdf_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE}
library(Hmisc)
library(mdsr)
library(babynames)
```

```{r}
BabynamesDist <- make_babynames_dist()
com_mal <- BabynamesDist %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  mutate(est_num_alive = sum(est_alive_today)) %>%
  filter(est_num_alive != 0 & est_num_alive >= 100000) %>%
  summarise(
    N = n(), est_num_alive = sum(est_alive_today),
    q1_age = wtd.quantile(age_today, est_alive_today, probs = 0.25),
    median_age = wtd.quantile(age_today, est_alive_today, probs = 0.5),
    q3_age = wtd.quantile(age_today, est_alive_today, probs = 0.75)) %>%
  arrange(median_age) %>%
  head(25)


w_plot <- ggplot(data = com_mal, aes(x = reorder(name, -median_age),  y = median_age)) + 
  xlab(NULL) + 
  ylab("Age (in years)") +
  ggtitle("Youngest Male Names", subtitle = "By estimated median age for Americans alive")


plot1 <- w_plot + 
  geom_linerange(
    aes(ymin = q1_age, ymax = q3_age),
    color = "#76bde0", 
    size = 5, 
    alpha = 0.7
  ) + 
  geom_point(fill = "#ed3324", colour = "white", size = 4, shape = 21) +
  coord_flip()

com_mal$name = as.factor(com_mal$name)

plot2 <- plot1 +
  geom_text(x=3, y = 25.2, label = '75th percentile▶',size = 3.2)+
  geom_text(x=3, y = 9.7, label = '◀25th',size = 3.2)

plot3 <- plot2 +
  geom_point(x=20, y = 24, fill = "#ed3324", colour = "white", size = 4, shape = 21) +
  geom_text(x=20, y = 25.3, label = "Median")

plot3

```
